export const initialValues = {
  tipo_nf: '',
  numero: '',
  pedido: '',
  faturamento: '',
  estado: '',
  nome_cpf_cnpj: '',
  transmissao_inicio: '',
  transmissao_fim: '',
  status: '',
  porta_copo: '',
  producao: '',
  vendedor: '',
  tipo_pedido: '',
  forma_pagamento: '',
  periodo_inicio: '',
  periodo_fim: '',
  transportadora: '',
  voucher: '',
}